settings:
  legacy:
    force: false
    interval: 0s
schema:
  - name: portfolio
    path: .
    commands: {}
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
  - name: portfolio
    path: /Users/aaronjanke/go/src/github.com/user/portfolio
    commands:
      build:
        status: true
      run:
        status: true
      generate:
        status: true
      install:
        status: true
    watcher:
      extensions:
        - go
      paths:
        - /
      ignored_paths:
        - .git
        - .realize
        - vendor
